#!/bin/bash
pkgver=5.15     # manually define the pkgver

### shouldn't need to edit anything below this line
pkgname='profile-sync-daemon'
startdir=$(pwd)
pkgdir="$startdir"/$pkgname'_'$pkgver'_all'
srcdir="$startdir/src"

# clean the build dirs
[[ -d "$srcdir/$pkgname-$pkgver" ]] && rm -rf "$srcdir/$pkgname-$pkgver"
[[ -d "$pkgdir" ]] && rm -rf "$pkgdir"
[[ ! -d "$srcdir" ]] && mkdir "$srcdir"

cd "$srcdir"

# get source
if [[ ! -f "v${pkgver}.tar.gz" ]]; then
	[[ ! -x /usr/bin/wget ]] && echo "Install wget and try again." && exit 0
	wget https://github.com/graysky2/profile-sync-daemon/archive/v${pkgver}.tar.gz
fi

tar zxf v${pkgver}.tar.gz
cd "$srcdir/$pkgname-$pkgver"

# make control stuff
install -Dm644 CHANGELOG "$pkgdir/DEBIAN/changelog"

# make the control file for dpkg-deb
cat > "$pkgdir/DEBIAN/control" << EOF
Package: $pkgname
Version: $pkgver
Architecture: all
Maintainer: Jayman [wantsumthin@gmail.com]
Installed-Size: 28
Depends: rsync, awk
Recommends: cron
Section: utils
Priority: optional
Homepage: https://wiki.archlinux.org/index.php/Profile-sync-daemon
Description: Symlinks and syncs browser profile dirs to RAM thus reducing HDD/SDD calls and speeding-up browsers.
 .
 Define which users will make use of the sync in /etc/psd.conf
EOF

# make the postinstall message for dpkg-deb
cat > "$pkgdir/DEBIAN/postinst" << EOF
#!/bin/sh
	echo '--------------------------------------------------------------------------'
	echo '  Define which users will make use of the sync in /etc/psd.conf'
	echo '  Read the manpage before use or see the wiki page'
	echo '  https://wiki.archlinux.org/index.php/Profile-sync-daemon'
	echo
	echo '  ALWAYS backup your profiles data before using utils like psd!'
	echo '--------------------------------------------------------------------------'
EOF
chmod +x $pkgdir/DEBIAN/postinst

# manpage
gzip -9 psd.manpage
install -Dm 0644 psd.manpage.gz "$pkgdir/usr/share/man/man1/$pkgname.1.gz"
ln -s "$pkgname.1.gz" "$pkgdir/usr/share/man/man1/psd.1.gz"

# /usr/bin
install -Dm755 $pkgname "$pkgdir/usr/bin/$pkgname"
ln -s "$pkgname" "$pkgdir/usr/bin/psd"

# now fixup the location of LOCKFILE in script for ubuntu
sed -i '/DAEMON_FILE=/ s,run,var\/run,' "$pkgdir/usr/bin/$pkgname"

# /etc
install -Dm644 psd.conf "$pkgdir/etc/psd.conf"
install -Dm755 psd.debian.init.example "$pkgdir/etc/init.d/psd"
install -Dm755 psd.cron.hourly "$pkgdir/etc/cron.hourly/psd-update"

# ubuntu does not mount /tmp to tmpfs by default so use /run/shm
sed -i 's/#VOLATILE="\/tmp"/VOLATILE="\/run\/shm"/' "$pkgdir/etc/psd.conf"

# make runlevel dirtree
for i in 0 1 2 3 4 5 6; do
	mkdir "$pkgdir/etc/rc$i.d"

	case $i in 
		0|6) linkname="K20psd" ;;
	1|2|3|4|5) linkname="S20psd";;
esac

cd "$pkgdir/etc/rc$i.d"
ln -s ../init.d/psd "$linkname"
done

# build the deb
cd "$startdir"
dpkg-deb --build "$pkgdir"
