#!/bin/bash

awk -v newsums="$(makepkg -g)" '
BEGIN {
  if (!newsums) exit 1
}

/^[[:blank:]]*(md|sha)[[:digit:]]+sums=/,/\)[[:blank:]]*$/ {
  if (!i) print newsums; i++
  next
}

1
' PKGBUILD > /tmp/PKGBUILD.new

[[ ! -s /tmp/PKGBUILD.new ]] && echo "Something is wrong, bailing." && exit 1

mv /tmp/PKGBUILD.new PKGBUILD
[[ -d src ]] && rm -rf src
